name: Build, push Docker images to docker Hub and update VPS

on:
  push:
    branches:
      - "main"

jobs:
  build_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Front image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          command: docker build --build-arg PUBLIC_WEBHOOK_DISCORD=${{ secrets.PUBLIC_WEBHOOK_DISCORD }} -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-front:latest .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-front:latest
      - name: Connect to VPS and Pull Front image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            cd website
            docker compose up -d front
